# Generated by Django 3.2 on 2021-05-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('adminId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('dob', models.DateField()),
                ('buyerId', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('sellerId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=254)),
                ('verified', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3)),
                ('address', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddresses',
            fields=[
                ('addressId', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=254)),
                ('buyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.buyers')),
            ],
        ),
    ]
