# Generated by Django 3.2 on 2021-05-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210508_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='address',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='admins',
            name='password',
            field=models.CharField(default='bcrypt_sha256$$2b$12$AbIWHcvYkZ.AgqP7aPp88Ows5Ve9hIJDAgzP.sjqddlC22P2SDmfW', max_length=254),
        ),
    ]
