export const VERIFIED_SELLERS_SUCCESS = 'VERIFIED_SELLERS_SUCCESS'
export const VERIFIED_SELLERS_REQUEST = 'VERIFIED_SELLERS_REQUEST'
export const VERIFIED_SELLERS_FAIL = 'VERIFIED_SELLERS_FAIL'
export const VERIFIED_SELLERS_RESET = 'VERIFIED_SELLERS_RESET'

export const UNVERIFIED_SELLERS_SUCCESS = 'UNVERIFIED_SELLERS_SUCCESS'
export const UNVERIFIED_SELLERS_REQUEST = 'UNVERIFIED_SELLERS_REQUEST'
export const UNVERIFIED_SELLERS_FAIL = 'UNVERIFIED_SELLERS_FAIL'
export const UNVERIFIED_SELLERS_RESET = 'UNVERIFIED_SELLERS_RESET'

export const ADMINS_LIST_SUCCESS = 'ADMINS_LIST_SUCCESS'
export const ADMINS_LIST_REQUEST = 'ADMINS_LIST_REQUEST'
export const ADMINS_LIST_FAIL = 'ADMINS_LIST_FAIL'
export const ADMINS_LIST_RESET = 'ADMINS_LIST_RESET'

export const DELIVER_PRODUCTS_SUCCESS = 'DELIVER_PRODUCTS_SUCCESS'
export const DELIVER_PRODUCTS_REQUEST = 'DELIVER_PRODUCTS_REQUEST'
export const DELIVER_PRODUCTS_FAIL = 'DELIVER_PRODUCTS_FAIL'
export const DELIVER_PRODUCTS_RESET = 'DELIVER_PRODUCTS_RESET'

export const RETURN_PRODUCTS_SUCCESS = 'RETURN_PRODUCTS_SUCCESS'
export const RETURN_PRODUCTS_REQUEST = 'RETURN_PRODUCTS_REQUEST'
export const RETURN_PRODUCTS_FAIL = 'RETURN_PRODUCTS_FAIL'
export const RETURN_PRODUCTS_RESET = 'RETURN_PRODUCTS_RESET'