export const ADDSTOCKS_NEW_SUCCESS = 'ADDSTOCKS_NEW_SUCCESS'
export const ADDSTOCKS_NEW_REQUEST = 'ADDSTOCKS_NEW_REQUEST'
export const ADDSTOCKS_NEW_FAIL = 'ADDSTOCKS_NEW_FAIL'
export const ADDSTOCKS_NEW_RESET = 'ADDSTOCKS_NEW_RESET'

export const ADDSTOCKS_OLD_SUCCESS = 'ADDSTOCKS_OLD_SUCCESS'
export const ADDSTOCKS_OLD_REQUEST = 'ADDSTOCKS_OLD_REQUEST'
export const ADDSTOCKS_OLD_FAIL = 'ADDSTOCKS_OLD_FAIL'
export const ADDSTOCKS_OLD_RESET = 'ADDSTOCKS_OLD_RESET'

export const USER_ORDERS_PLACED_SUCCESS = 'USER_ORDERS_PLACED_SUCCESS'
export const USER_ORDERS_PLACED_REQUEST = 'USER_ORDERS_PLACED_REQUEST'
export const USER_ORDERS_PLACED_FAIL = 'USER_ORDERS_PLACED_FAIL'
export const USER_ORDERS_PLACED_RESET = 'USER_ORDERS_PLACED_RESET'

export const ADDOFFERS_SUCCESS = 'ADDOFFERS_SUCCESS'
export const ADDOFFERS_REQUEST = 'ADDOFFERS_REQUEST'
export const ADDOFFERS_FAIL = 'ADDOFFERS_FAIL'
export const ADDOFFERS_RESET = 'ADDOFFERS_RESET'

export const REMOVEOFFERS_SUCCESS = 'REMOVEOFFERS_SUCCESS'
export const REMOVEOFFERS_REQUEST = 'REMOVEOFFERS_REQUEST'
export const REMOVEOFFERS_FAIL = 'REMOVEOFFERS_FAIL'
export const REMOVEOFFERS_RESET = 'REMOVEOFFERS_RESET'