export const ADDSTOCKS_NEW_SUCCESS = 'ADDSTOCKS_NEW_SUCCESS'
export const ADDSTOCKS_NEW_REQUEST = 'ADDSTOCKS_NEW_REQUEST'
export const ADDSTOCKS_NEW_FAIL = 'ADDSTOCKS_NEW_FAIL'
export const ADDSTOCKS_NEW_RESET = 'ADDSTOCKS_NEW_RESET'

export const ADDSTOCKS_OLD_SUCCESS = 'ADDSTOCKS_OLD_SUCCESS'
export const ADDSTOCKS_OLD_REQUEST = 'ADDSTOCKS_OLD_REQUEST'
export const ADDSTOCKS_OLD_FAIL = 'ADDSTOCKS_OLD_FAIL'
export const ADDSTOCKS_OLD_RESET = 'ADDSTOCKS_OLD_RESET'