# Generated by Django 3.2 on 2021-05-05 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('details', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stockId', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('dateOfAddition', models.DateTimeField(auto_now=True)),
                ('totalQuantity', models.IntegerField()),
                ('availableQuantity', models.IntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.products')),
                ('sellerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.sellers')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('ratingId', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review', models.CharField(blank=True, max_length=254)),
                ('reviewedAt', models.DateTimeField(auto_now_add=True)),
                ('buyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.buyers')),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.products')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.BigAutoField(primary_key=True, serialize=False)),
                ('totalAmount', models.IntegerField()),
                ('paymentMethod', models.CharField(choices=[('"cash', '"Cash'), ('on', 'On'), ('delivery"', 'Delivery"'), ('"paypal"', '"Paypal"')], max_length=20)),
                ('orderedAt', models.DateTimeField(auto_now_add=True)),
                ('addressId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shippingaddresses')),
                ('buyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.buyers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('serialId', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('orderedItemId', models.BigAutoField(primary_key=True, serialize=False)),
                ('finalDate', models.DateTimeField(auto_now=True)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.orders')),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offerId', models.BigAutoField(primary_key=True, serialize=False)),
                ('discountPercent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cartId', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('buyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.buyers')),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.stocks')),
            ],
        ),
    ]
